### ISSUE TITLE
Cannot seem to get it to work 

### ISSUE THREAD

**Issue by tidusjar** [Drewster727/plexpy-influxdb-export#1]
So trying to get this to work

Info:
Python version 2.7
Command run:

    plexpy_influxdb_export.py --plexpyhost localhost --plexpyapikey APIKEY_REMOVED --plexpyport 8084

Nothing output and nothing happens.

I created the database in InfluxDb called `plexpy`  there are no measurements.

It would be useful to print something out to the console, since there is no feedback at the moment :)

**Comment by Drewster727** [comment]
https://github.com/Drewster727/plexpy-influxdb-export/commit/9ed616f2450fb01e2a505637579a83ed7f32bab7

for you my good sir!

**Comment by tidusjar** [comment]
I'm getting the following over and over

    'unicode' object has no attribute 'read'

**Comment by Drewster727** [comment]
hmmm. is this windows? what version of python, influxdb, and plexpy?

**Comment by tidusjar** [comment]
Windows, Python 2.7, InfluxDb can't really tell you since I compiled it myself using Go (Not officially supported on Windows, but I'm pretty sure it's the latest), PlexPy is version 1.4.6 (cannot upgrade due to some Timezone issue).

I've narrowed it down to the `json.load` changing it to `json.loads` returns `No JSON object could be decoded`
http://stackoverflow.com/questions/3150584/passing-a-json-object-through-post-using-python

But my Python is very very basic...

**Comment by tidusjar** [comment]
More info:

    requests.get('{0}{1}'.format(plexpy_url, '&cmd=get_activity'), verify=False).text

returns `No JSON object could be decoded`

**Comment by tidusjar** [comment]
Ah, got it. I had a base url/root url set!

**Comment by tidusjar** [comment]
So changing it to json.loads works.

**Comment by Drewster727** [comment]
nice. ok, I will test on my box tonight and update that.

**Comment by tidusjar** [comment]
I also added a PR to support the base url, can you add your dashboard into the repo? Saves me having to configure mine

**Comment by Drewster727** [comment]
hey man, sorry for the late reply. will add it soon.

**Comment by tidusjar** [comment]
That's cool dude :)
