### ISSUE TITLE
Direct Stream noted as Transcode

### ISSUE THREAD

**Issue by svenvg93** [Drewster727/plexpy-influxdb-export#10]
I pulled the latest version as you told me yesterday. But I ran into a issue. When I create a graph the direct streams are noted as transcode. See Attachment. 
Maybe its a problem with plexpy, but the graphs in plexpy are correct.
![grafana](https://user-images.githubusercontent.com/4511676/29888033-b292d180-8dbf-11e7-8f1a-677781383810.png)
![plexpy](https://user-images.githubusercontent.com/4511676/29888035-b468a7b4-8dbf-11e7-8350-ac6a9842c682.png)

**Comment by Drewster727** [comment]
Do me a favor and hit this url in your browser when you have a transcode and direct stream (as you had in your screenshots):

<plexpyurl>/api/v2?apikey=<plexpy_api_key>&cmd=get_activity

Send me the resulting json. Thanks!

**Comment by svenvg93** [comment]
I get the following output.`{"response": {"message": null, "data": {"stream_count": "2", "sessions": [{"transcode_width": "1280", "user_thumb": "https://plex.tv/users/72f6d8841be953b7/avatar?c=1504039883", "labels": [], "height": "720", "parent_rating_key": "2540", "audio_codec": "ac3", "parent_title": "Season 7", "rating_key": "11018", "transcode_video_codec": "h264", "transcode_audio_codec": "ac3", "user_id": 385993, "thumb": "/library/metadata/11018/thumb/1495272483", "title": "Hu a'e ke ahi lanakila a Kamaile", "throttled": "1", "platform": "iOS", "transcode_height": "720", "transcode_container": "mpegts", "media_type": "episode", "video_resolution": "720p", "grandparent_rating_key": "634", "audio_channels": "6", "full_title": "Hawaii Five-0  - Hu a'e ke ahi lanakila a Kamaile", "ip_address": "192.168.0.103", "transcode_audio_channels": "6", "transcode_speed": "0.0", "transcode_protocol": "hls", "progress_percent": "51", "bif_thumb": "", "grandparent_title": "Hawaii Five-0 ", "parent_media_index": "7", "machine_id": "58AA652D-6D0B-4AC6-8DA5-D4936205AB80", "art": "/library/metadata/634/art/1495272485", "player": "iPhone van Sven", "year": "2016", "duration": "2624000", "session_key": "8", "transcode_key": "/transcode/sessions/EBDC82C5-7051-451D-A719-37EA4461315C", "container": "mpegts", "indexes": 0, "video_decision": "copy", "state": "playing", "audio_decision": "copy", "view_offset": "1361007", "section_id": "1", "aspect_ratio": "", "user": "svenvg93", "transcode_decision": "copy", "bitrate": "4406", "video_framerate": "", "media_index": "4", "content_rating": "TV-14", "friendly_name": "svenvg93", "parent_thumb": "/library/metadata/2540/thumb/1495272485", "video_codec": "h264", "grandparent_thumb": "/library/metadata/634/thumb/1495272485", "transcode_progress": 60, "width": "1280"}, {"transcode_width": "1920", "user_thumb": "https://plex.tv/users/72f6d8841be953b7/avatar?c=1504039883", "labels": [], "height": "1080", "parent_rating_key": "112", "audio_codec": "ac3", "parent_title": "Season 1", "rating_key": "113", "transcode_video_codec": "h264", "transcode_audio_codec": "ac3", "user_id": 385993, "thumb": "/library/metadata/113/thumb/1494550270", "title": "Pilot", "throttled": "1", "platform": "iOS", "transcode_height": "1080", "transcode_container": "mpegts", "media_type": "episode", "video_resolution": "1080p", "grandparent_rating_key": "93", "audio_channels": "6", "full_title": "The Big Bang Theory - Pilot", "ip_address": "192.168.0.106", "transcode_audio_channels": "6", "transcode_speed": "0.0", "transcode_protocol": "hls", "progress_percent": "2", "bif_thumb": "", "grandparent_title": "The Big Bang Theory", "parent_media_index": "1", "machine_id": "BE5C7B1C-4AD7-45E6-990E-D4ADF6D421B0", "art": "/library/metadata/93/art/1494550287", "player": "iPad van Sven", "year": "2007", "duration": "1378379", "session_key": "9", "transcode_key": "/transcode/sessions/87A3F1BF-E63C-4E09-8C50-359A55A51A54", "container": "mpegts", "indexes": 0, "video_decision": "copy", "state": "playing", "audio_decision": "transcode", "view_offset": "30673", "section_id": "1", "aspect_ratio": "", "user": "svenvg93", "transcode_decision": "transcode", "bitrate": "12758", "video_framerate": "", "media_index": "1", "content_rating": "TV-PG", "friendly_name": "svenvg93", "parent_thumb": "/library/metadata/112/thumb/1493945358", "video_codec": "h264", "grandparent_thumb": "/library/metadata/93/thumb/1494550287", "transcode_progress": 12, "width": "1920"}]}, "result": "success"}}`

**Comment by Drewster727** [comment]
Hawaii Five-O
`"video_decision": "copy",
"audio_decision": "copy",
"transcode_decision": "copy",`

Big Bang Theory
`"video_decision": "copy",
"audio_decision": "transcode",
"transcode_decision": "transcode"`

Those are the items I look at. So, I'm assuming Hawaii Five-O was the direct stream and Big Bang was the transcode? If so, I'll just need to look for "copy" -- I had my logic incorrectly looking for "direct stream"

**Comment by Drewster727** [comment]
Try the latest version. Warning: I did not get a chance to test it.

**Comment by svenvg93** [comment]
Now I'm not getting any data :(
Maybe the traceback will help you.
`sven@NUC:/usr/local/bin/plexpy-influxdb-export$ python /usr/local/bin/plexpy-influxdb-export/plexpy_influxdb_export.py --plexpyhost 192.168.0.12 --plexpyapikey cd42f89fa81c5e44a8d377f3ccb1b509 --influxdbhost 192.168.0.12
Started
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
'decision'
^CTraceback (most recent call last):
  File "/usr/local/bin/plexpy-influxdb-export/plexpy_influxdb_export.py", line 207, in <module>
    main()
  File "/usr/local/bin/plexpy-influxdb-export/plexpy_influxdb_export.py", line 21, in main
    init_exporting(args.interval, plexpy_url, influxdb_client)
  File "/usr/local/bin/plexpy-influxdb-export/plexpy_influxdb_export.py", line 197, in init_exporting
    time.sleep(interval)
KeyboardInterrupt`

If I need to test something just let me know!

**Comment by Drewster727** [comment]
Oops, fixed! Try now :)

**Comment by svenvg93** [comment]
Yes, its works! Now I see a Direct stream instead of Transcode
![fixed](https://user-images.githubusercontent.com/4511676/29891685-45485f66-8dcc-11e7-9e68-a809ab322934.png)

Thanks for the quick fix!
Quick other question, what kind of other informatie can you export form Plexpy to Influxdb?

**Comment by Drewster727** [comment]
![image](https://user-images.githubusercontent.com/4528753/29892065-cddcc1bc-8d92-11e7-847c-0f7a7272f87b.png)

That's primarily what I track in plexpy, but you can export most/all of the plexpy data, they have a pretty good API.
