### ISSUE TITLE
More 'Question' than 'Issue' - Tautulli compatibility?

### ISSUE THREAD

**Issue by 2wheelsdown** [Drewster727/plexpy-influxdb-export#11]
Does this work with the latest version of PlexPy, known as Tautulli?

I'm not very good with python stuff, and all I'm getting is "No module named requests"...?  Cheers.

**Comment by Drewster727** [comment]
> Does this work with the latest version of PlexPy, known as Tautulli?
I upgraded to tautulli earlier this week and my exporter appears to still be working.

> I'm not very good with python stuff, and all I'm getting is "No module named requests"...? Cheers.
Try this:
`pip install requests `

**Comment by 2wheelsdown** [comment]
Thanks - I was actually just in the middle of editing my question to apologise and say I'd just found out about "easy_install.exe <module>"

Just added the 'requests' and 'influxdb' modules and now it appears to be working.

Thanks for your input.
