### ISSUE TITLE
Invalid syntax: Line 60 print str(e)

### ISSUE THREAD

**Issue by Saltystew** [Drewster727/plexpy-influxdb-export#6]
![shot_170615_215725](https://user-images.githubusercontent.com/20447447/27208791-c96e9bea-5215-11e7-9ed3-d10454c20509.png)

**Comment by Drewster727** [comment]
I believe that is proper syntax. What version of python are you using?

**Comment by Saltystew** [comment]
I have both 2.7 and 3.6.1 installed

**Comment by Drewster727** [comment]
ok, have you tried it with both? Just running "python" from the command line doesn't really give an indication as to which version is executing the script. run a python -v

**Comment by Saltystew** [comment]
So which should it be using?

I get this when I run python -v

![shot_170615_223514](https://user-images.githubusercontent.com/20447447/27209637-fab4bc8e-521a-11e7-9101-fbed6c40164d.png)

**Comment by Drewster727** [comment]
Thanks @Saltystew I will document the version in the readme.
