### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by evanrich** [Drewster727/plexpy-influxdb-export#7]
```
root@metrics:/lib/systemd/system# /usr/bin/python /opt/plexpy-influxdb-export/plexpy_influxdb_export.py --plexpywebprotocol https --plexpyhost plexpy.home --plexpyport 8181 --plexpyapikey 9<censored>6 --influxdbhost 192.168.1.144 --influxdbuser influxdb --influxdbpassword influxdb
```

```
Started
404: 404 page not found

404: 404 page not found

404: 404 page not found
```

python 2.7.9
plexpy: 1.4.20
plex: 1.7.3.x

i also had to do pip install -U requests, because it was giving me an error originally about not being able to import something..  Any idea what the 404 is from?

url manually works in browser:
```
https://plexpy.home:8181/api/v2?apikey=9<redacted>6&cmd=get_activity
```

results in:

```
{"response": {"message": null, "data": {"stream_count": "0", "sessions": []}, "result": "success"}}
```

**Comment by evanrich** [comment]
solved this myself by this link
[https://stackoverflow.com/questions/36846975/influxdb-python-404-page-not-found/36952335#36952335](https://stackoverflow.com/questions/36846975/influxdb-python-404-page-not-found/36952335#36952335)

specifically, 
```
pip install --upgrade influxdb
```

then it worked

**Comment by Drewster727** [comment]
hmm. What version of influxdb were you on before the upgrade?

**Comment by evanrich** [comment]
I was (and still am) on Influx server 1.2.4.   I think this was a python module or something it updated
