### ISSUE TITLE
Added Direct stream as a option

### ISSUE THREAD

**Issue by svenvg93** [Drewster727/plexpy-influxdb-export#9]
First of all, I love your script! Thanks for sharing.
I wanted to make a graph based on the stream type. But I only can choose for direct play and transcode. If I want to see the direct stream count I need to choose transcode. Is it possible to added direct stream as a separate option like direct play and transcode?

**Comment by Drewster727** [comment]
@svenvg93 thanks!
Pull down the latest code. It has direct play and direct stream split out.
